# API Configuration for Network Templates
# This file contains the external API endpoints and settings

api:
  # External API endpoint (update this to your actual API)
  base_url: "https://f901829ad604.ngrok-free.app"
  endpoint: "/api/v1/network-templates/updated"
  
  # Full URL will be: https://127.0.0.1:5001/api/v1/network-templates/updated
  
  # Timeout settings
  timeout: 30
  retry_attempts: 3
  
  # Headers to include in API calls
  headers:
    Content-Type: "application/json"
    User-Agent: "network-templates-github-action/1.0"
    X-Source: "github-actions"
  
  # Authentication configuration
  authentication:
    type: "bearer_token"
    token: "secret-token" 

# Environment-specific overrides (optional)
environments:
  production:
    base_url: https://f901829ad604.ngrok-free.app"
    timeout: 30
  
  staging:
    base_url: "https://f901829ad604.ngrok-free.app"
    timeout: 15
    
  development:
    base_url: "https://f901829ad604.ngrok-free.app"
    timeout: 10

# Notification settings
notifications:
  include_diff: true
  include_metadata: true
  max_payload_size: "1MB"
