apiVersion: v1
kind: ConfigMap
metadata:
  name: device-list
  namespace: default
  labels:
    app: device-rollout
data:
  # List of 100 device IDs for rollout
  devices.json: |
    {
      "total_devices": 100,
      "devices": [
        "device-001", "device-002", "device-003", "device-004", "device-005",
        "device-006", "device-007", "device-008", "device-009", "device-010",
        "device-011", "device-012", "device-013", "device-014", "device-015",
        "device-016", "device-017", "device-018", "device-019", "device-020",
        "device-021", "device-022", "device-023", "device-024", "device-025",
        "device-026", "device-027", "device-028", "device-029", "device-030",
        "device-031", "device-032", "device-033", "device-034", "device-035",
        "device-036", "device-037", "device-038", "device-039", "device-040",
        "device-041", "device-042", "device-043", "device-044", "device-045",
        "device-046", "device-047", "device-048", "device-049", "device-050",
        "device-051", "device-052", "device-053", "device-054", "device-055",
        "device-056", "device-057", "device-058", "device-059", "device-060",
        "device-061", "device-062", "device-063", "device-064", "device-065",
        "device-066", "device-067", "device-068", "device-069", "device-070",
        "device-071", "device-072", "device-073", "device-074", "device-075",
        "device-076", "device-077", "device-078", "device-079", "device-080",
        "device-081", "device-082", "device-083", "device-084", "device-085",
        "device-086", "device-087", "device-088", "device-089", "device-090",
        "device-091", "device-092", "device-093", "device-094", "device-095",
        "device-096", "device-097", "device-098", "device-099", "device-100"
      ],
      "rollout_strategy": {
        "step1": {"percentage": 20, "devices": ["device-001", "device-002", "device-003", "device-004", "device-005", "device-006", "device-007", "device-008", "device-009", "device-010", "device-011", "device-012", "device-013", "device-014", "device-015", "device-016", "device-017", "device-018", "device-019", "device-020"]},
        "step2": {"percentage": 40, "devices": ["device-001", "device-002", "device-003", "device-004", "device-005", "device-006", "device-007", "device-008", "device-009", "device-010", "device-011", "device-012", "device-013", "device-014", "device-015", "device-016", "device-017", "device-018", "device-019", "device-020", "device-021", "device-022", "device-023", "device-024", "device-025", "device-026", "device-027", "device-028", "device-029", "device-030", "device-031", "device-032", "device-033", "device-034", "device-035", "device-036", "device-037", "device-038", "device-039", "device-040"]},
        "step3": {"percentage": 60, "devices": ["device-001", "device-002", "device-003", "device-004", "device-005", "device-006", "device-007", "device-008", "device-009", "device-010", "device-011", "device-012", "device-013", "device-014", "device-015", "device-016", "device-017", "device-018", "device-019", "device-020", "device-021", "device-022", "device-023", "device-024", "device-025", "device-026", "device-027", "device-028", "device-029", "device-030", "device-031", "device-032", "device-033", "device-034", "device-035", "device-036", "device-037", "device-038", "device-039", "device-040", "device-041", "device-042", "device-043", "device-044", "device-045", "device-046", "device-047", "device-048", "device-049", "device-050", "device-051", "device-052", "device-053", "device-054", "device-055", "device-056", "device-057", "device-058", "device-059", "device-060"]},
        "step4": {"percentage": 80, "devices": ["device-001", "device-002", "device-003", "device-004", "device-005", "device-006", "device-007", "device-008", "device-009", "device-010", "device-011", "device-012", "device-013", "device-014", "device-015", "device-016", "device-017", "device-018", "device-019", "device-020", "device-021", "device-022", "device-023", "device-024", "device-025", "device-026", "device-027", "device-028", "device-029", "device-030", "device-031", "device-032", "device-033", "device-034", "device-035", "device-036", "device-037", "device-038", "device-039", "device-040", "device-041", "device-042", "device-043", "device-044", "device-045", "device-046", "device-047", "device-048", "device-049", "device-050", "device-051", "device-052", "device-053", "device-054", "device-055", "device-056", "device-057", "device-058", "device-059", "device-060", "device-061", "device-062", "device-063", "device-064", "device-065", "device-066", "device-067", "device-068", "device-069", "device-070", "device-071", "device-072", "device-073", "device-074", "device-075", "device-076", "device-077", "device-078", "device-079", "device-080"]},
        "step5": {"percentage": 100, "devices": ["device-001", "device-002", "device-003", "device-004", "device-005", "device-006", "device-007", "device-008", "device-009", "device-010", "device-011", "device-012", "device-013", "device-014", "device-015", "device-016", "device-017", "device-018", "device-019", "device-020", "device-021", "device-022", "device-023", "device-024", "device-025", "device-026", "device-027", "device-028", "device-029", "device-030", "device-031", "device-032", "device-033", "device-034", "device-035", "device-036", "device-037", "device-038", "device-039", "device-040", "device-041", "device-042", "device-043", "device-044", "device-045", "device-046", "device-047", "device-048", "device-049", "device-050", "device-051", "device-052", "device-053", "device-054", "device-055", "device-056", "device-057", "device-058", "device-059", "device-060", "device-061", "device-062", "device-063", "device-064", "device-065", "device-066", "device-067", "device-068", "device-069", "device-070", "device-071", "device-072", "device-073", "device-074", "device-075", "device-076", "device-077", "device-078", "device-079", "device-080", "device-081", "device-082", "device-083", "device-084", "device-085", "device-086", "device-087", "device-088", "device-089", "device-090", "device-091", "device-092", "device-093", "device-094", "device-095", "device-096", "device-097", "device-098", "device-099", "device-100"]}
      }
    }
  
  # Configuration for API endpoint
  api-config.yaml: |
    api:
      # Railway app endpoint for device configuration updates
      endpoint: "https://discerning-surprise-production.up.railway.app/api/v1/start-config-update-on-devices"
      timeout: "30s"
      retry_attempts: 2
      headers:
        content-type: "application/json"
      payload_format: |
        {
          "devices": ["device-001", "device-002", "..."]
        }
