apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: default
  labels:
    app: test-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: test-app
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-bg-active
  namespace: default
  labels:
    app: test-app-bg
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: test-app-bg
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-bg-preview
  namespace: default
  labels:
    app: test-app-bg
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: test-app-bg
